### ISSUE TITLE
Can't import package if there are no packages

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#134]
v1.4.2-dev+ec1cd8b8

I exported a package from one install of fb2k.

I then tried to import the package into a second copy of fb2k which had a new install of SMP. The package failed to load & I obtained the error:

```The system cannot find the path specified: "Z:\f2k\foobar2000\foo_spider_monkey_panel\tmp\unpacked_package", "Z:\f2k\foobar2000\foo_spider_monkey_panel\packages\{F85C9EF0-778B-46DD-AF20-F4BE831360DD}"```

May be a required folder was missing/not created. I say this since if I create a new package first, then try the import it works. Otherwise it's all looking good so far.

**Comment by TheQwertiest** [comment]
Thanks for reporting! Should be fixed in the dev build (once it's done).

**Comment by Wil-B** [comment]
OK thanks for that.

But I still can't properly install a package on my main foobar2000 install.

I exported a package from test portable install. Then I tried to import into main install which is a standard install.

I obtained the following error.

```create_directories: Access is denied.: "C:\Program Files (x86)\foobar2000\foo_spider_monkey_panel\tmp\unpacked_package"```

I assumed it should be putting packages in the profile path (rather than the Program Files location it's tried to access above). So I manually copied the necessary to the foobar2000 profile folder & that seems to be working.

**Comment by Wil-B** [comment]
Another issue with the package manager. I see the following error when trying to update packages. It ends up with a corrupted package as some files are removed but not all. The new package fails to install.  It seems that the images folder or images therein are the problem. I use assets\images with the images loaded using gdi.Image

```'remove_all: Access is denied'```

**Comment by TheQwertiest** [comment]
This is a separate problem form the one in the OP: https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/137

**Comment by marc2k3** [comment]
Access denied errors will be due to this...

https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/ce39bb098a9ea150baf78d18c60f7ee6617598f7/foo_spider_monkey_panel/component_paths.cpp#L30L38

It's using the main foobar2000 folder which will work fine in portable mode but fail when installed normally inside program files.

**Comment by TheQwertiest** [comment]
Good catch! Should've put the temp folder in the profile as well.
